#include <iostream>
#include <cmath>
#include <algorithm>

using namespace std;

long int createAccountNumber(int count){
    long int branchCode = 2600000;
    int branchLocationCode = 21000;
    return branchCode + branchLocationCode + count;
}

// this logic generated by GPT-4.0, it is used to calculate the average annual balance based on current balance and minimum balance
double getAverageAnnualBalance(double balance , double minBalance){
    if (balance < minBalance) {
        return balance; 
    }

    double daysAtMin = 30.0;
    double daysAtCurrent = rand() % 365;
    double totalDays = 365.0;
    
    double averageBalance = ((balance * daysAtCurrent) + (minBalance * daysAtMin)) / totalDays;
    
    return averageBalance;
}

// this logic generated by GPT-4.0, it is used to calculate the transaction per day limit based on average annual balance
int calculatetrxnPerDayLimit(double averageAnnualBalance) {
    // 1. Handle edge cases for negative or zero balances
    if (averageAnnualBalance <= 0) {
        return 1000; // Minimum baseline limit for basic accounts
    }

    double calculatedLimit = 0;

    // 2. Define tiered logic based on balance brackets
    if (averageAnnualBalance < 5000) {
        // Low balance tier: 10% of balance or a $2,000 max
        calculatedLimit = min(2000.0, averageAnnualBalance * 0.10);
    } 
    else if (averageAnnualBalance >= 5000 && averageAnnualBalance < 25000) {
        // Mid tier: 5% of balance, up to $5,000
        calculatedLimit = min(5000.0, averageAnnualBalance * 0.05);
    } 
    else if (averageAnnualBalance >= 25000 && averageAnnualBalance < 100000) {
        // High tier: 3% of balance, up to $15,000
        calculatedLimit = min(15000.0, averageAnnualBalance * 0.03);
    } 
    else {
        // Premium tier: 2% of balance, capped at $50,000
        calculatedLimit = min(50000.0, averageAnnualBalance * 0.02);
    }

    // 3. Enforce an absolute minimum limit so the account remains usable
    if (calculatedLimit < 1000) {
        calculatedLimit = 1000;
    }

    // 4. Return as a rounded integer
    return (int) round(calculatedLimit);
}



int createChequeBookNumber(int count){
    int branchLocationCode = 21000;
    return branchLocationCode + count;
}

double calculateProfit(int shareCount , int perSharePrice , double sellingPrice){
    // return (shareCount * perSharePrice) - sellingPrice;
    return sellingPrice - (shareCount * perSharePrice);
}